#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/wmake/scripts/AllwmakeParseArguments

#------------------------------------------------------------------------------

# Build main sootlib first
wmake $targetType .

# Build examples
wmake $targetType examples/simple
wmake $targetType examples/burner_flame

#------------------------------------------------------------------------------
